language: node_js
node_js:
  - latest  # or the version you want to use

services:
  - docker

before_install:
  - docker build -t siowyenchong/reactapp -f Dockerfile.dev .

script:
  - docker run siowyenchong/reactapp npm run test -- --coverage
